import type { ArcModelProfileKey } from "./model-profiles.ts";

const ARC_SUBAGENT_GENERATED_MARKER = "<!-- generated by @sentiolabs/pi-arc arc-subagents -->";
const ARC_SUBAGENT_SYNC_VERSION = "2";
const MAX_PROSE_BYTES = 64 * 1024;
const MAX_ARRAY_ENTRIES = 1_024;

export interface ArcGeneratedAgentMetadata { sourceSha256: string; modelResolutionSource: string; modelsConfigSha256: string; generatedAt: string; }
export interface ArcResolvedAgentDefinition {
  name: string; sourceName: string; profileKey: ArcModelProfileKey; description: string; systemPrompt: string;
  model?: string; tools?: string[]; systemPromptMode: "replace"; inheritProjectContext: true;
  inheritGlobalContext: false; inheritSkills: false;
}

interface ArcParsedAgentSource {
  description: string;
  prompt: string;
  tools?: string[];
}

function assertText(value: string, field: string, maxBytes = MAX_PROSE_BYTES): string {
  if (!value.trim()) throw new TypeError(`${field} must not be blank`);
  if (value.includes("\0")) throw new TypeError(`${field} must not contain NUL`);
  if (Buffer.byteLength(value, "utf8") > maxBytes) throw new TypeError(`${field} exceeds ${maxBytes} UTF-8 bytes`);
  return value;
}

function parseScalar(value: string, field: string): string {
  const trimmed = value.trim();
  if (trimmed.startsWith('"')) {
    let parsed: unknown;
    try {
      parsed = JSON.parse(trimmed);
    } catch {
      throw new TypeError(`${field} must be a valid quoted string`);
    }
    if (typeof parsed !== "string") throw new TypeError(`${field} must be a string`);
    return parsed;
  }
  if (trimmed.startsWith("'") && trimmed.endsWith("'") && trimmed.length >= 2) {
    return trimmed.slice(1, -1).replace(/''/g, "'");
  }
  return trimmed;
}

function parseTools(lines: string[], startIndex: number, inlineValue: string): { tools?: string[]; endIndex: number } {
  let tools: string[];
  let endIndex = startIndex;
  if (inlineValue.trim()) {
    const raw = inlineValue.trim();
    if (raw.startsWith("[") && raw.endsWith("]")) {
      let parsed: unknown;
      try {
        parsed = JSON.parse(raw);
      } catch {
        throw new TypeError("tools must be a comma-separated string or JSON string array");
      }
      if (!Array.isArray(parsed) || parsed.some((entry) => typeof entry !== "string")) {
        throw new TypeError("tools must contain only strings");
      }
      tools = parsed;
    } else {
      tools = raw.split(",").map((entry) => entry.trim());
    }
  } else {
    tools = [];
    for (let index = startIndex + 1; index < lines.length; index += 1) {
      const match = /^\s+-\s*(.*)$/.exec(lines[index]);
      if (!match) break;
      tools.push(parseScalar(match[1], `tools[${tools.length}]`));
      endIndex = index;
    }
  }
  if (tools.length === 0 || tools.length > MAX_ARRAY_ENTRIES) throw new TypeError(`tools must contain between 1 and ${MAX_ARRAY_ENTRIES} entries`);
  const normalized = tools.map((tool, index) => assertText(tool.trim(), `tools[${index}]`));
  if (new Set(normalized).size !== normalized.length) throw new TypeError("tools must not contain duplicates");
  return { tools: normalized, endIndex };
}

function parseArcAgentSource(sourceMarkdown: string): ArcParsedAgentSource {
  assertText(sourceMarkdown, "sourceMarkdown", Number.MAX_SAFE_INTEGER);
  const normalized = sourceMarkdown.replace(/\r\n?/g, "\n");
  const lines = normalized.split("\n");
  if (lines[0] !== "---") throw new TypeError("sourceMarkdown must begin with frontmatter");
  const closingIndex = lines.indexOf("---", 1);
  if (closingIndex < 0) throw new TypeError("sourceMarkdown frontmatter is not closed");

  let description: string | undefined;
  let tools: string[] | undefined;
  for (let index = 1; index < closingIndex; index += 1) {
    const line = lines[index];
    if (!line.trim() || /^\s*#/.test(line)) continue;
    const field = /^([A-Za-z][A-Za-z0-9_-]*):\s*(.*)$/.exec(line);
    if (!field) {
      if (/^\s+-/.test(line)) throw new TypeError(`unexpected frontmatter list entry at line ${index + 1}`);
      throw new TypeError(`invalid frontmatter at line ${index + 1}`);
    }
    const [, key, rawValue] = field;
    if (key === "description") {
      if (description !== undefined) throw new TypeError("description must appear only once");
      description = parseScalar(rawValue, "description");
    } else if (key === "tools") {
      if (tools !== undefined) throw new TypeError("tools must appear only once");
      const parsed = parseTools(lines.slice(0, closingIndex), index, rawValue);
      tools = parsed.tools;
      index = parsed.endIndex;
    }
  }

  const prompt = lines.slice(closingIndex + 1).join("\n").trim();
  return {
    description: assertText(description ?? "", "description"),
    prompt: assertText(prompt, "prompt"),
    ...(tools ? { tools } : {}),
  };
}

function validateDefinition(definition: ArcResolvedAgentDefinition): void {
  assertText(definition.name, "name");
  assertText(definition.sourceName, "sourceName");
  assertText(definition.description, "description");
  assertText(definition.systemPrompt, "prompt");
  if (definition.model !== undefined) assertText(definition.model, "model");
  if (definition.tools !== undefined) {
    if (definition.tools.length === 0 || definition.tools.length > MAX_ARRAY_ENTRIES) throw new TypeError(`tools must contain between 1 and ${MAX_ARRAY_ENTRIES} entries`);
    definition.tools.forEach((tool, index) => assertText(tool, `tools[${index}]`));
  }
  if (definition.systemPromptMode !== "replace"
    || definition.inheritProjectContext !== true
    || definition.inheritGlobalContext !== false
    || definition.inheritSkills !== false) {
    throw new TypeError("definition contains invalid specialist policy fields");
  }
}

export function buildArcResolvedAgentDefinition(input: { name: string; sourceName: string; profileKey: ArcModelProfileKey; sourceMarkdown: string; resolvedModel?: string }): ArcResolvedAgentDefinition {
  assertText(input.name, "name");
  assertText(input.sourceName, "sourceName");
  const parsed = parseArcAgentSource(input.sourceMarkdown);
  const model = input.resolvedModel === undefined ? undefined : assertText(input.resolvedModel.trim(), "resolvedModel");
  return {
    name: input.name,
    sourceName: input.sourceName,
    profileKey: input.profileKey,
    description: parsed.description,
    systemPrompt: parsed.prompt,
    ...(model ? { model } : {}),
    ...(parsed.tools ? { tools: [...parsed.tools] } : {}),
    systemPromptMode: "replace",
    inheritProjectContext: true,
    inheritGlobalContext: false,
    inheritSkills: false,
  };
}

function yamlStringValue(value: string): string {
  return JSON.stringify(value);
}

export function renderArcResolvedAgentDefinition(input: { definition: ArcResolvedAgentDefinition; metadata: ArcGeneratedAgentMetadata }): string {
  validateDefinition(input.definition);
  assertText(input.metadata.sourceSha256, "metadata.sourceSha256");
  assertText(input.metadata.modelResolutionSource, "metadata.modelResolutionSource");
  assertText(input.metadata.modelsConfigSha256, "metadata.modelsConfigSha256");
  assertText(input.metadata.generatedAt, "metadata.generatedAt");

  const frontmatter = [
    "---",
    `name: ${input.definition.name}`,
    `description: ${yamlStringValue(input.definition.description)}`,
    input.definition.model ? `model: ${input.definition.model}` : undefined,
    input.definition.tools?.length ? `tools: ${input.definition.tools.join(", ")}` : undefined,
    "systemPromptMode: replace",
    "inheritProjectContext: true",
    "inheritGlobalContext: false",
    "inheritSkills: false",
    "---",
  ].filter((line): line is string => line !== undefined).join("\n");
  const metadata = [
    ARC_SUBAGENT_GENERATED_MARKER,
    `<!-- sync-version: ${ARC_SUBAGENT_SYNC_VERSION} -->`,
    `<!-- source: agents/${input.definition.sourceName}.md -->`,
    `<!-- source-sha256: ${input.metadata.sourceSha256} -->`,
    `<!-- model-profile-key: ${input.definition.profileKey} -->`,
    `<!-- model-resolution-source: ${input.metadata.modelResolutionSource} -->`,
    `<!-- models-config-sha256: ${input.metadata.modelsConfigSha256} -->`,
    `<!-- generated-at: ${input.metadata.generatedAt} -->`,
  ].join("\n");
  return `${frontmatter}\n${metadata}\n\n${input.definition.systemPrompt}`;
}

export function toRuntimeAgentDefinition(definition: ArcResolvedAgentDefinition): {
  description: string; systemPrompt: string; model?: string; tools?: string[]; systemPromptMode: "replace";
  inheritProjectContext: true; inheritGlobalContext: false; inheritSkills: false;
} {
  validateDefinition(definition);
  return {
    description: definition.description,
    systemPrompt: definition.systemPrompt,
    ...(definition.model ? { model: definition.model } : {}),
    ...(definition.tools ? { tools: [...definition.tools] } : {}),
    systemPromptMode: "replace" as const,
    inheritProjectContext: true as const,
    inheritGlobalContext: false as const,
    inheritSkills: false as const,
  };
}
