import { createHash } from "node:crypto";
import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";

import type { ArcModelProfileKey } from "./model-profiles.ts";

export const ARC_SUBAGENT_GENERATED_MARKER = "<!-- generated by @sentiolabs/pi-arc arc-subagents -->";
const ARC_SUBAGENT_LEGACY_GENERATED_MARKER = "<!-- generated by @sentiolabs/pi-arc arc-subagents-sync -->";
export const ARC_SUBAGENT_SYNC_VERSION = "2";

export type ArcSubagentMaterializationReason =
  | "session_start"
  | "arc_models_save"
  | "manual_repair";

export type ArcSubagentScope = "user" | "project";

export type ArcSubagentWriteStatus = "written" | "unchanged" | "skipped" | "failed";

export interface ArcSubagentWriteResult {
  agent: string;
  source: string;
  target: string;
  status: ArcSubagentWriteStatus;
  reason?: string;
}

export interface ArcSubagentShadowWarning {
  agent: string;
  projectPath: string;
  userPath: string;
  generated: boolean;
  stale: boolean;
  message: string;
}

export interface ArcSubagentMaterializationResult {
  reason: ArcSubagentMaterializationReason;
  scope: ArcSubagentScope;
  targetDir: string;
  writes: ArcSubagentWriteResult[];
  shadows: ArcSubagentShadowWarning[];
}

export interface ArcSubagentTemplate {
  sourceName: string;
  targetName: string;
  profileKey: ArcModelProfileKey;
}

export interface ArcSubagentParsedSource {
  prompt: string;
  description?: string;
  tools?: string[];
}

export interface ArcSubagentRenderInput {
  targetName: string;
  sourceName: string;
  sourceMarkdown: string;
  parsedSource: ArcSubagentParsedSource;
  resolvedModel?: string;
  modelProfileKey: ArcModelProfileKey;
  modelResolutionSource: string;
  modelsConfigHash: string;
  generatedAt: string;
}

export const ARC_PI_SUBAGENTS = [
  { source: "builder", target: "arc-builder", profileKey: "builder" },
  { source: "doc-writer", target: "arc-doc-writer", profileKey: "docWriter" },
  { source: "spec-reviewer", target: "arc-spec-reviewer", profileKey: "specReviewer" },
  { source: "code-reviewer", target: "arc-code-reviewer", profileKey: "codeReviewer" },
  { source: "evaluator", target: "arc-evaluator", profileKey: "evaluator" },
  { source: "issue-manager", target: "arc-issue-manager", profileKey: "issueManager" },
] as const;

export function resolveArcSubagentDir(
  scope: ArcSubagentScope,
  cwd: string,
  homeDir: string,
  options: { legacyUserDir?: boolean } = {},
): string {
  if (scope === "project") return path.join(cwd, ".pi", "agents");
  if (options.legacyUserDir) return path.join(homeDir, ".pi", "agent", "agents");
  return path.join(homeDir, ".agents");
}

export function isGeneratedArcSubagent(markdown: string | undefined): boolean {
  return Boolean(
    markdown?.includes(ARC_SUBAGENT_GENERATED_MARKER)
      || markdown?.includes(ARC_SUBAGENT_LEGACY_GENERATED_MARKER),
  );
}

export function buildArcSubagentMetadata(input: {
  sourceName: string;
  sourceSha256: string;
  modelProfileKey: string;
  modelResolutionSource: string;
  modelsConfigSha256: string;
  generatedAt: string;
}): string {
  return [
    ARC_SUBAGENT_GENERATED_MARKER,
    `<!-- sync-version: ${ARC_SUBAGENT_SYNC_VERSION} -->`,
    `<!-- source: agents/${input.sourceName}.md -->`,
    `<!-- source-sha256: ${input.sourceSha256} -->`,
    `<!-- model-profile-key: ${input.modelProfileKey} -->`,
    `<!-- model-resolution-source: ${input.modelResolutionSource} -->`,
    `<!-- models-config-sha256: ${input.modelsConfigSha256} -->`,
    `<!-- generated-at: ${input.generatedAt} -->`,
  ].join("\n");
}

function sha256Text(text: string): string {
  return createHash("sha256").update(text).digest("hex");
}

function yamlStringValue(value: string): string {
  return JSON.stringify(value);
}

function errorCode(error: unknown): string | undefined {
  if (typeof error !== "object" || error === null || !("code" in error)) return undefined;
  const code = (error as { code?: unknown }).code;
  return typeof code === "string" ? code : undefined;
}

function withoutGeneratedAt(markdown: string): string {
  return markdown.replace(/^<!-- generated-at: .* -->$/m, "<!-- generated-at: <ignored> -->");
}

function equivalentGeneratedArcSubagent(actual: string, expected: string): boolean {
  return withoutGeneratedAt(actual) === withoutGeneratedAt(expected);
}

async function isDirectory(dir: string): Promise<boolean> {
  try {
    return (await stat(dir)).isDirectory();
  } catch {
    return false;
  }
}

async function nearestArcProjectRoot(cwd: string): Promise<string> {
  let current = path.resolve(cwd);
  const root = path.parse(current).root;
  while (true) {
    if (await isDirectory(path.join(current, ".pi")) || await isDirectory(path.join(current, ".agents"))) {
      return current;
    }
    if (current === root) return path.resolve(cwd);
    current = path.dirname(current);
  }
}

async function arcProjectShadowPaths(cwd: string, target: string): Promise<string[]> {
  const projectRoot = await nearestArcProjectRoot(cwd);
  return [
    path.join(projectRoot, ".agents", `${target}.md`),
    path.join(projectRoot, ".pi", "agents", `${target}.md`),
  ];
}

export function buildArcSubagentMarkdown(input: ArcSubagentRenderInput): string {
  const metadata = buildArcSubagentMetadata({
    sourceName: input.sourceName,
    sourceSha256: sha256Text(input.sourceMarkdown),
    modelProfileKey: input.modelProfileKey,
    modelResolutionSource: input.modelResolutionSource,
    modelsConfigSha256: input.modelsConfigHash,
    generatedAt: input.generatedAt,
  });

  const frontmatter = [
    "---",
    `name: ${input.targetName}`,
    input.parsedSource.description ? `description: ${yamlStringValue(input.parsedSource.description)}` : undefined,
    input.resolvedModel ? `model: ${input.resolvedModel}` : undefined,
    input.parsedSource.tools?.length ? `tools: ${input.parsedSource.tools.join(", ")}` : undefined,
    "systemPromptMode: replace",
    "inheritProjectContext: true",
    "inheritSkills: false",
    "---",
  ]
    .filter((line): line is string => Boolean(line))
    .join("\n");

  const body = input.parsedSource.prompt;
  return `${frontmatter}\n${metadata}\n\n${body}`;
}

export async function materializeArcSubagents(input: {
  reason: ArcSubagentMaterializationReason;
  scope: ArcSubagentScope;
  cwd: string;
  homeDir: string;
  agentsDir: string;
  modelsConfigSha256: string;
  renderAgent: (source: string, target: string) => Promise<string>;
  legacyUserDir?: boolean;
  allowLegacyUserDirFallback?: boolean;
}): Promise<ArcSubagentMaterializationResult> {
  return materializeArcSubagentsOnce(input);
}

async function materializeArcSubagentsOnce(input: Parameters<typeof materializeArcSubagents>[0]): Promise<ArcSubagentMaterializationResult> {
  const targetDir = resolveArcSubagentDir(input.scope, input.cwd, input.homeDir, { legacyUserDir: input.legacyUserDir });
  try {
    await mkdir(targetDir, { recursive: true });
  } catch (error) {
    if (input.scope === "user" && input.allowLegacyUserDirFallback && !input.legacyUserDir) {
      return materializeArcSubagentsOnce({ ...input, legacyUserDir: true, allowLegacyUserDirFallback: false });
    }
    throw error;
  }

  const writes: ArcSubagentWriteResult[] = [];
  const shadows: ArcSubagentShadowWarning[] = [];

  for (const { source, target } of ARC_PI_SUBAGENTS) {
    const sourcePath = path.join(input.agentsDir, `${source}.md`);
    const targetPath = path.join(targetDir, `${target}.md`);
    const projectPaths = input.scope === "user" ? await arcProjectShadowPaths(input.cwd, target) : [];

    try {
      const rendered = await input.renderAgent(source, target);

      let existing: string | undefined;
      try {
        existing = await readFile(targetPath, "utf8");
      } catch (error) {
        if (errorCode(error) !== "ENOENT") {
          writes.push({
            agent: target,
            source: sourcePath,
            target: targetPath,
            status: "failed",
            reason: `could not read existing target: ${error instanceof Error ? error.message : String(error)}`,
          });
          continue;
        }
        existing = undefined;
      }

      if (existing === undefined) {
        try {
          await writeFile(targetPath, rendered, "utf8");
          writes.push({ agent: target, source: sourcePath, target: targetPath, status: "written" });
        } catch (error) {
          writes.push({
            agent: target,
            source: sourcePath,
            target: targetPath,
            status: "failed",
            reason: `could not write target: ${error instanceof Error ? error.message : String(error)}`,
          });
          continue;
        }
      } else if (!isGeneratedArcSubagent(existing)) {
        writes.push({
          agent: target,
          source: sourcePath,
          target: targetPath,
          status: "skipped",
          reason: "existing file is missing generated marker; preserving user edits",
        });
      } else if (existing === rendered || equivalentGeneratedArcSubagent(existing, rendered)) {
        writes.push({ agent: target, source: sourcePath, target: targetPath, status: "unchanged" });
      } else {
        try {
          await writeFile(targetPath, rendered, "utf8");
          writes.push({ agent: target, source: sourcePath, target: targetPath, status: "written" });
        } catch (error) {
          writes.push({
            agent: target,
            source: sourcePath,
            target: targetPath,
            status: "failed",
            reason: `could not write target: ${error instanceof Error ? error.message : String(error)}`,
          });
          continue;
        }
      }

      for (const projectPath of projectPaths) {
        if (path.resolve(projectPath) === path.resolve(targetPath)) continue;
        try {
          const projectContent = await readFile(projectPath, "utf8");
          const generated = isGeneratedArcSubagent(projectContent);
          const hasCurrentModelConfig = projectContent.includes(`models-config-sha256: ${input.modelsConfigSha256}`);
          shadows.push({
            agent: target,
            projectPath,
            userPath: targetPath,
            generated,
            stale: generated && (!hasCurrentModelConfig || !equivalentGeneratedArcSubagent(projectContent, rendered)),
            message: generated
              ? `Project shadow detected at ${projectPath}; pi-subagents project scope wins over user scope ${targetPath}`
              : `Project shadow detected at ${projectPath} (non-generated); pi-subagents project scope wins over user scope ${targetPath}`,
          });
        } catch (error) {
          if (errorCode(error) !== "ENOENT") {
            shadows.push({
              agent: target,
              projectPath,
              userPath: targetPath,
              generated: false,
              stale: false,
              message: `Could not inspect project shadow at ${projectPath}; pi-subagents project scope may still win over user scope ${targetPath}: ${error instanceof Error ? error.message : String(error)}`,
            });
          }
        }
      }
    } catch (error) {
      writes.push({
        agent: target,
        source: sourcePath,
        target: targetPath,
        status: "failed",
        reason: error instanceof Error ? error.message : String(error),
      });
    }
  }

  return {
    reason: input.reason,
    scope: input.scope,
    targetDir,
    writes,
    shadows,
  };
}
