import { test } from 'node:test';
import assert from 'node:assert/strict';

import {
  buildArcResolvedAgentDefinition,
  renderArcResolvedAgentDefinition,
  toRuntimeAgentDefinition,
} from '../extensions/arc/agent-definitions.ts';

function pick(value, keys) {
  return Object.fromEntries(keys.filter((key) => key in value).map((key) => [key, value[key]]));
}

const policyFields = [
  'description',
  'systemPrompt',
  'model',
  'tools',
  'systemPromptMode',
  'inheritProjectContext',
  'inheritGlobalContext',
  'inheritSkills',
];

const metadata = {
  sourceSha256: 'a'.repeat(64),
  modelResolutionSource: 'profile',
  modelsConfigSha256: 'b'.repeat(64),
  generatedAt: '2026-07-17T00:00:00.000Z',
};

test('resolved ordinary specialist definition projects every runtime policy field', () => {
  const definition = buildArcResolvedAgentDefinition({
    name: 'arc-builder', sourceName: 'builder', profileKey: 'builder',
    sourceMarkdown: '---\ndescription: "Build: safely"\ntools: read,write,edit\n---\nDo the task.',
    resolvedModel: 'provider/model',
  });
  assert.deepEqual(definition, {
    name: 'arc-builder',
    sourceName: 'builder',
    profileKey: 'builder',
    description: 'Build: safely',
    systemPrompt: 'Do the task.',
    model: 'provider/model',
    tools: ['read', 'write', 'edit'],
    systemPromptMode: 'replace',
    inheritProjectContext: true,
    inheritGlobalContext: false,
    inheritSkills: false,
  });

  const runtime = toRuntimeAgentDefinition(definition);
  assert.deepEqual(pick(runtime, policyFields), pick(definition, policyFields));
  assert.notEqual(runtime.tools, definition.tools);
  for (const forbidden of ['name', 'source', 'sourceName', 'profileKey', 'filePath', 'modelProvider', 'fast', 'memory', 'disabled']) {
    assert.equal(forbidden in runtime, false);
  }
});

test('builder parses ordinary list frontmatter without model-policy or provider resolution', () => {
  const definition = buildArcResolvedAgentDefinition({
    name: 'arc-builder',
    sourceName: 'builder',
    profileKey: 'builder',
    sourceMarkdown: [
      '---',
      'description: Build one scoped task.',
      'tools:',
      '  - bash',
      '  - read',
      'model: ignored-tier-alias',
      '---',
      '',
      '# Builder',
    ].join('\n'),
  });
  assert.equal(definition.description, 'Build one scoped task.');
  assert.equal(definition.systemPrompt, '# Builder');
  assert.deepEqual(definition.tools, ['bash', 'read']);
  assert.equal('model' in definition, false, 'source model aliases are not resolved by this module');
});

test('file rendering preserves marker, metadata ordering, policy, and colon-bearing description meaning', () => {
  const description = 'Build: safely and precisely';
  const definition = buildArcResolvedAgentDefinition({
    name: 'arc-builder',
    sourceName: 'builder',
    profileKey: 'builder',
    sourceMarkdown: `---\ndescription: ${description}\ntools: read, write\n---\nDo the task.`,
    resolvedModel: 'provider/model',
  });
  const rendered = renderArcResolvedAgentDefinition({ definition, metadata });

  assert.ok(rendered.startsWith('---\nname: arc-builder\n'));
  const descriptionLine = rendered.split('\n').find((line) => line.startsWith('description: '));
  assert.equal(JSON.parse(descriptionLine.slice('description: '.length)), description);
  for (const line of [
    'model: provider/model',
    'tools: read, write',
    'systemPromptMode: replace',
    'inheritProjectContext: true',
    'inheritGlobalContext: false',
    'inheritSkills: false',
  ]) assert.ok(rendered.includes(`\n${line}\n`), `missing ${line}`);

  const orderedMetadata = [
    '<!-- generated by @sentiolabs/pi-arc arc-subagents -->',
    '<!-- sync-version: 2 -->',
    '<!-- source: agents/builder.md -->',
    `<!-- source-sha256: ${metadata.sourceSha256} -->`,
    '<!-- model-profile-key: builder -->',
    '<!-- model-resolution-source: profile -->',
    `<!-- models-config-sha256: ${metadata.modelsConfigSha256} -->`,
    '<!-- generated-at: 2026-07-17T00:00:00.000Z -->',
  ].join('\n');
  assert.ok(rendered.includes(orderedMetadata));
  assert.ok(rendered.endsWith('\n\nDo the task.'));
});

test('blank or NUL description and prompt fail before rendering', () => {
  const base = {
    name: 'arc-builder',
    sourceName: 'builder',
    profileKey: 'builder',
  };
  for (const sourceMarkdown of [
    '---\ndescription: ""\n---\nPrompt.',
    '---\ndescription: Valid\n---\n   ',
    '---\ndescription: "Bad\\u0000description"\n---\nPrompt.',
    '---\ndescription: Valid\n---\nBad\u0000prompt',
  ]) {
    assert.throws(() => buildArcResolvedAgentDefinition({ ...base, sourceMarkdown }), /description|prompt|sourceMarkdown/i);
  }
});

test('definition validation rejects malformed supplied values and rendering does not mutate definitions', () => {
  assert.throws(() => buildArcResolvedAgentDefinition({
    name: '', sourceName: 'builder', profileKey: 'builder',
    sourceMarkdown: '---\ndescription: Valid\n---\nPrompt.',
  }));
  assert.throws(() => buildArcResolvedAgentDefinition({
    name: 'arc-builder', sourceName: 'builder', profileKey: 'builder',
    sourceMarkdown: '---\ndescription: Valid\ntools: read,,write\n---\nPrompt.',
  }));
  assert.throws(() => buildArcResolvedAgentDefinition({
    name: 'arc-builder', sourceName: 'builder', profileKey: 'builder',
    sourceMarkdown: '---\ndescription: Valid\n---\nPrompt.', resolvedModel: ' ',
  }));

  const definition = buildArcResolvedAgentDefinition({
    name: 'arc-builder', sourceName: 'builder', profileKey: 'builder',
    sourceMarkdown: '---\ndescription: Valid\ntools: read,write\n---\nPrompt.',
  });
  const before = structuredClone(definition);
  renderArcResolvedAgentDefinition({ definition, metadata });
  assert.deepEqual(definition, before);
});
