import { createHash } from "node:crypto";
import { spawn } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { StringEnum } from "@mariozechner/pi-ai";
import {
  DEFAULT_MAX_BYTES,
  DEFAULT_MAX_LINES,
  formatSize,
  truncateTail,
  type ExtensionAPI,
  type ExtensionContext,
} from "@mariozechner/pi-coding-agent";
import { Type } from "typebox";

type ArcCommandResult = {
  code: number | null;
  stdout: string;
  stderr: string;
};

const WORKFLOW_SKILLS: Array<{ command: string; skill: string; description: string }> = [
  {
    command: "arc-brainstorm",
    skill: "arc-brainstorm",
    description: "Use arc-brainstorm for design discovery and trade-off analysis",
  },
  {
    command: "arc-plan",
    skill: "arc-plan",
    description: "Use arc-plan to break an approved design into arc implementation tasks",
  },
  {
    command: "arc-build",
    skill: "arc-build",
    description: "Use arc-build to orchestrate implementation of arc tasks",
  },
  {
    command: "arc-debug",
    skill: "arc-debug",
    description: "Use arc-debug for structured root-cause investigation",
  },
  {
    command: "arc-review",
    skill: "arc-review",
    description: "Use arc-review to review changes against an arc task",
  },
  {
    command: "arc-verify",
    skill: "arc-verify",
    description: "Use arc-verify for evidence-based completion checks",
  },
  {
    command: "arc-finish",
    skill: "arc-finish",
    description: "Use arc-finish to wrap up a session and persist handoff context",
  },
  {
    command: "arc-source-sync",
    skill: "arc-source-sync",
    description: "Maintainer-only: sync pi-arc resources from the Arc source plugin",
  },
];

function outputOf(result: ArcCommandResult): string {
  const stdout = result.stdout.trim();
  const stderr = result.stderr.trim();
  if (stdout && stderr) return `${stdout}\n\nstderr:\n${stderr}`;
  return stdout || stderr || `(exit code ${result.code ?? "unknown"}, no output)`;
}

type ArcAgentName = "builder" | "code-reviewer" | "doc-writer" | "evaluator" | "issue-manager" | "spec-reviewer";

const ARC_AGENT_NAMES = [
  "builder",
  "code-reviewer",
  "doc-writer",
  "evaluator",
  "issue-manager",
  "spec-reviewer",
] as const;

const ARC_PI_SUBAGENTS = [
  { source: "builder", target: "arc-builder" },
  { source: "doc-writer", target: "arc-doc-writer" },
  { source: "spec-reviewer", target: "arc-spec-reviewer" },
  { source: "code-reviewer", target: "arc-code-reviewer" },
  { source: "evaluator", target: "arc-evaluator" },
  { source: "issue-manager", target: "arc-issue-manager" },
] as const;

const ARC_SUBAGENT_GENERATED_MARKER = "<!-- generated by @sentiolabs/pi-arc arc-subagents-sync -->";
const ARC_SUBAGENT_SYNC_VERSION = "1";

const EXTENSION_DIR = path.dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = path.resolve(EXTENSION_DIR, "..");
const AGENTS_DIR = path.join(PACKAGE_ROOT, "agents");

type ArcModelTier = "nano" | "small" | "standard" | "large";

type ArcModelTierMap = Record<ArcModelTier, string>;

const DEFAULT_ARC_MODEL_TIERS: ArcModelTierMap = {
  nano: "openai-codex/gpt-5.4-nano",
  small: "openai-codex/gpt-5.4-mini",
  standard: "openai-codex/gpt-5.3-codex",
  large: "openai-codex/gpt-5.5",
};

const MODEL_TIER_ALIASES: Record<string, ArcModelTier> = {
  nano: "nano",
  haiku: "small",
  mini: "small",
  small: "small",
  sonnet: "standard",
  standard: "standard",
  opus: "large",
  large: "large",
};

function parseAgentMarkdown(markdown: string): { prompt: string; description?: string; model?: string; tools?: string[] } {
  if (!markdown.startsWith("---")) return { prompt: markdown.trim() };
  const end = markdown.indexOf("\n---", 3);
  if (end === -1) return { prompt: markdown.trim() };

  const frontmatter = markdown.slice(3, end).trim().split(/\r?\n/);
  const body = markdown.slice(end + "\n---".length).trim();
  let description: string | undefined;
  let model: string | undefined;
  const tools: string[] = [];
  let inTools = false;

  for (const line of frontmatter) {
    const trimmed = line.trim();
    if (trimmed.startsWith("description:")) {
      description = trimmed.slice("description:".length).trim().replace(/^['\"]|['\"]$/g, "");
      inTools = false;
      continue;
    }
    if (trimmed.startsWith("model:")) {
      model = trimmed.slice("model:".length).trim().replace(/^['\"]|['\"]$/g, "");
      inTools = false;
      continue;
    }
    if (trimmed.startsWith("tools:")) {
      inTools = true;
      const inline = trimmed.slice("tools:".length).trim();
      if (inline) tools.push(...inline.split(",").map((tool) => tool.trim()).filter(Boolean));
      continue;
    }
    if (inTools && trimmed.startsWith("-")) {
      tools.push(trimmed.slice(1).trim());
      continue;
    }
    if (trimmed && !trimmed.startsWith("#")) inTools = false;
  }

  return { prompt: body, description, model, tools: tools.length > 0 ? tools : undefined };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

async function readJsonFile(filePath: string): Promise<Record<string, unknown> | undefined> {
  try {
    const content = await readFile(filePath, "utf8");
    const parsed = JSON.parse(content) as unknown;
    return isRecord(parsed) ? parsed : undefined;
  } catch {
    return undefined;
  }
}

function applyTierOverrides(target: ArcModelTierMap, settings: Record<string, unknown> | undefined) {
  const arc = isRecord(settings?.arc) ? settings.arc : undefined;
  const modelTiers = isRecord(arc?.modelTiers) ? arc.modelTiers : undefined;
  if (!modelTiers) return;

  for (const tier of Object.keys(DEFAULT_ARC_MODEL_TIERS) as ArcModelTier[]) {
    const value = modelTiers[tier];
    if (typeof value === "string" && value.trim()) target[tier] = value.trim();
  }
}

async function loadArcModelTiers(cwd: string): Promise<ArcModelTierMap> {
  const tiers: ArcModelTierMap = { ...DEFAULT_ARC_MODEL_TIERS };

  applyTierOverrides(tiers, await readJsonFile(path.join(homedir(), ".pi", "agent", "settings.json")));

  const projectSettings: string[] = [];
  let dir = path.resolve(cwd);
  const root = path.parse(dir).root;
  while (true) {
    projectSettings.push(path.join(dir, ".pi", "settings.json"));
    if (dir === root) break;
    dir = path.dirname(dir);
  }

  for (const settingsPath of projectSettings.reverse()) {
    applyTierOverrides(tiers, await readJsonFile(settingsPath));
  }

  return tiers;
}

async function modelPattern(model: string | undefined, cwd: string): Promise<string | undefined> {
  if (!model) return undefined;
  const trimmed = model.trim();
  const normalized = trimmed.toLowerCase();
  if (!normalized) return undefined;

  const tier = MODEL_TIER_ALIASES[normalized];
  if (!tier) return trimmed;

  const tiers = await loadArcModelTiers(cwd);
  return tiers[tier];
}

function runPiSubprocess(args: string[], cwd: string, signal?: AbortSignal): Promise<ArcCommandResult> {
  return new Promise((resolve) => {
    const child = spawn("pi", args, { cwd, stdio: ["ignore", "pipe", "pipe"] });
    let stdout = "";
    let stderr = "";
    let settled = false;

    const finish = (result: ArcCommandResult) => {
      if (settled) return;
      settled = true;
      if (signal) signal.removeEventListener("abort", abort);
      resolve(result);
    };

    const abort = () => child.kill("SIGTERM");
    if (signal) {
      if (signal.aborted) abort();
      else signal.addEventListener("abort", abort, { once: true });
    }

    child.stdout.on("data", (chunk) => {
      stdout += chunk.toString();
    });
    child.stderr.on("data", (chunk) => {
      stderr += chunk.toString();
    });
    child.on("error", (error) => finish({ code: 127, stdout, stderr: stderr + error.message }));
    child.on("close", (code) => finish({ code, stdout, stderr }));
  });
}

function truncatedOutput(text: string): string {
  const truncation = truncateTail(text, { maxBytes: DEFAULT_MAX_BYTES, maxLines: DEFAULT_MAX_LINES });
  if (!truncation.truncated) return truncation.content;
  return `${truncation.content}\n\n[Output truncated: ${truncation.outputLines} of ${truncation.totalLines} lines (${formatSize(
    truncation.outputBytes,
  )} of ${formatSize(truncation.totalBytes)}).]`;
}

type ArcSubagentScope = "project" | "user";

type ArcSubagentSyncSkip = {
  file: string;
  reason: string;
};

function parseArcSubagentScopeArg(rawArgs: string): { scope: ArcSubagentScope; error?: string } {
  const tokens = rawArgs
    .trim()
    .split(/\s+/)
    .filter(Boolean);

  if (tokens.length === 0) return { scope: "project" };
  if (tokens.length > 1) {
    return {
      scope: "project",
      error: `Unsupported arguments: ${tokens.join(" ")}. Use one of: project, --project, user, --user.`,
    };
  }

  const token = tokens[0]?.toLowerCase();
  if (token === "project" || token === "--project") return { scope: "project" };
  if (token === "user" || token === "--user") return { scope: "user" };
  return {
    scope: "project",
    error: `Unknown scope '${tokens[0]}'. Use one of: project, --project, user, --user.`,
  };
}

function resolveArcSubagentDir(scope: ArcSubagentScope, cwd: string): string {
  if (scope === "user") return path.join(homedir(), ".pi", "agent", "agents");
  return path.join(cwd, ".pi", "agents");
}

function yamlStringValue(value: string): string {
  return JSON.stringify(value);
}

function formatArcSubagentTools(tools: string[] | undefined): string | undefined {
  if (!tools || tools.length === 0) return undefined;
  const normalized = tools.map((tool) => tool.trim().toLowerCase()).filter(Boolean);
  if (normalized.length === 0) return undefined;
  return normalized.join(", ");
}

function buildArcSubagentMarkdown(
  targetName: string,
  sourceName: string,
  sourceMarkdown: string,
  parsedSource: ReturnType<typeof parseAgentMarkdown>,
  resolvedModel: string | undefined,
): string {
  const frontmatter: string[] = ["---", `name: ${targetName}`];
  if (parsedSource.description) frontmatter.push(`description: ${yamlStringValue(parsedSource.description)}`);
  if (resolvedModel) frontmatter.push(`model: ${resolvedModel}`);

  const toolsValue = formatArcSubagentTools(parsedSource.tools);
  if (toolsValue) frontmatter.push(`tools: ${toolsValue}`);

  frontmatter.push(
    "systemPromptMode: replace",
    "inheritProjectContext: true",
    "inheritSkills: false",
    "---",
  );

  const sourceSha = createHash("sha256").update(sourceMarkdown).digest("hex");
  return `${frontmatter.join("\n")}\n\n${ARC_SUBAGENT_GENERATED_MARKER}\n<!-- sync-version: ${ARC_SUBAGENT_SYNC_VERSION} -->\n<!-- source: agents/${sourceName}.md -->\n<!-- source-sha256: ${sourceSha} -->\n\n${parsedSource.prompt.trim()}\n`;
}

function runArcWithStdin(
  args: string[],
  stdin: unknown,
  cwd: string,
  signal?: AbortSignal,
  timeoutMs = 15_000,
): Promise<ArcCommandResult> {
  return new Promise((resolve) => {
    const child = spawn("arc", args, {
      cwd,
      stdio: ["pipe", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";
    let settled = false;

    const finish = (result: ArcCommandResult) => {
      if (settled) return;
      settled = true;
      clearTimeout(timeout);
      if (signal) signal.removeEventListener("abort", abort);
      resolve(result);
    };

    const abort = () => {
      child.kill("SIGTERM");
    };

    const timeout = setTimeout(() => {
      stderr += `Timed out after ${timeoutMs}ms`;
      child.kill("SIGTERM");
    }, timeoutMs);

    if (signal) {
      if (signal.aborted) abort();
      else signal.addEventListener("abort", abort, { once: true });
    }

    child.stdout.on("data", (chunk) => {
      stdout += chunk.toString();
    });
    child.stderr.on("data", (chunk) => {
      stderr += chunk.toString();
    });
    child.stdin.on("error", (error) => {
      stderr += error.message;
    });
    child.on("error", (error) => {
      finish({ code: 127, stdout, stderr: stderr + error.message });
    });
    child.on("close", (code) => {
      finish({ code, stdout, stderr });
    });

    child.stdin.end(`${JSON.stringify(stdin)}\n`);
  });
}

export default function arcExtension(pi: ExtensionAPI) {
  let primeCache = "";
  let primeError = "";
  let lastPrimeAt = 0;

  async function runArc(args: string[], ctx: ExtensionContext, timeout = 15_000): Promise<ArcCommandResult> {
    const result = await pi.exec("arc", args, { timeout, signal: ctx.signal });
    return {
      code: result.code,
      stdout: result.stdout ?? "",
      stderr: result.stderr ?? "",
    };
  }

  async function refreshPrime(ctx: ExtensionContext): Promise<boolean> {
    try {
      const result = await runArc(["prime"], ctx, 20_000);
      lastPrimeAt = Date.now();
      if (result.code === 0) {
        primeCache = result.stdout.trim();
        primeError = "";
        return true;
      }
      primeError = outputOf(result);
      return false;
    } catch (error) {
      lastPrimeAt = Date.now();
      primeError = error instanceof Error ? error.message : String(error);
      return false;
    }
  }

  function sendArcMessage(title: string, body: string) {
    pi.sendMessage({
      customType: "arc",
      content: `## ${title}\n\n${body}`,
      display: true,
    });
  }

  async function sendArcCommandOutput(ctx: ExtensionContext, title: string, args: string[], timeout = 30_000) {
    const result = await runArc(args, ctx, timeout);
    const status = result.code === 0 ? "info" : "error";
    if (ctx.hasUI) ctx.ui.notify(`arc ${args.join(" ")} ${result.code === 0 ? "completed" : "failed"}`, status);
    sendArcMessage(title, `\`arc ${args.join(" ")}\` exited with code ${result.code}.\n\n\`\`\`\n${outputOf(result)}\n\`\`\``);
  }

  pi.registerTool({
    name: "arc_agent",
    label: "Arc Agent",
    description:
      "Run a bundled Arc specialist agent (builder, reviewer, issue-manager, etc.) in a fresh Pi subprocess. Output is truncated to 50KB/2000 lines.",
    promptSnippet: "Delegate Arc issue-management, implementation, review, docs, and evaluation tasks to bundled specialist agents.",
    promptGuidelines: [
      "Prefer true pi-subagents Arc specialists (arc-builder, arc-issue-manager, arc-code-reviewer, etc.) when synced so long runs can be monitored with /subagents-status.",
      "For bulk issue creation, do not use arc_agent issue-manager when subagent({ action: \"list\" }) shows arc-issue-manager; dispatch arc-issue-manager asynchronously instead.",
      "Use arc_agent only as the self-contained fallback when Arc pi-subagents definitions are unavailable or a workflow skill explicitly asks for the fallback.",
      "Right-size fallback arc_agent dispatches with model tiers: nano for bulk CLI issue creation, small for mechanical/docs tasks, standard for normal contained work, large for complex or high-risk work.",
    ],
    parameters: Type.Object({
      agent: StringEnum(ARC_AGENT_NAMES),
      task: Type.String({ description: "Complete task prompt to give the subagent." }),
      model: Type.Optional(Type.String({ description: "Optional Pi model pattern override, e.g. nano, haiku, sonnet, opus." })),
      isolation: Type.Optional(StringEnum(["none", "worktree"] as const)),
    }),
    async execute(_toolCallId: string, params: any, signal: AbortSignal | undefined, onUpdate: any, ctx: ExtensionContext) {
      if (params.isolation === "worktree") {
        throw new Error("arc_agent worktree isolation is not implemented yet. Use isolation='none' or run tasks sequentially.");
      }

      const agent = params.agent as ArcAgentName;
      const agentPath = path.join(AGENTS_DIR, `${agent}.md`);
      const markdown = await readFile(agentPath, "utf8");
      const config = parseAgentMarkdown(markdown);
      const requestedModel = params.model ?? config.model;
      const selectedModel = await modelPattern(requestedModel, ctx.cwd);
      const selectedTools = config.tools?.map((tool) => tool.toLowerCase()).join(",");

      const args = ["-p", "--no-session", "--system-prompt", config.prompt];
      if (selectedModel) args.push("--model", selectedModel);
      if (selectedTools) args.push("--tools", selectedTools);
      args.push(params.task);

      onUpdate?.({
        content: [
          {
            type: "text",
            text: `Running arc_agent ${agent}${selectedModel ? ` with model ${selectedModel}` : ""}...`,
          },
        ],
        details: { agent, requestedModel, model: selectedModel, tools: selectedTools },
      });

      const result = await runPiSubprocess(args, ctx.cwd, signal);
      const combined = outputOf(result);
      const text = truncatedOutput(combined);

      if (result.code !== 0) {
        throw new Error(`arc_agent ${agent} failed with exit code ${result.code}.\n\n${text}`);
      }

      return {
        content: [{ type: "text", text }],
        details: {
          agent,
          requestedModel,
          model: selectedModel,
          tools: selectedTools,
          exitCode: result.code,
          stdout: result.stdout,
          stderr: result.stderr,
        },
      };
    },
  } as any);

  pi.on("session_start", async (_event, ctx) => {
    const ok = await refreshPrime(ctx);
    if (ctx.hasUI) {
      ctx.ui.notify(ok ? "arc context loaded" : "arc context unavailable", ok ? "info" : "warning");
    }

    const payload = {
      harness: "pi",
      event: "session_start",
      cwd: ctx.cwd,
      sessionFile: ctx.sessionManager.getSessionFile(),
      timestamp: new Date().toISOString(),
    };

    // Best-effort compatibility with arc AI session tracking. Older arc versions may not
    // support this payload outside Claude; failures are intentionally non-fatal.
    await runArcWithStdin(["ai", "session", "start", "--stdin"], payload, ctx.cwd, ctx.signal).catch(() => undefined);
  });

  pi.on("session_before_compact", async (_event, ctx) => {
    await refreshPrime(ctx);
  });

  pi.on("before_agent_start", async (event, ctx) => {
    if (!primeCache && !primeError) {
      await refreshPrime(ctx);
    }

    const context = primeCache
      ? `<arc-context last-updated="${new Date(lastPrimeAt).toISOString()}">\n${primeCache}\n</arc-context>`
      : primeError
        ? `<arc-context status="unavailable">\narc prime failed: ${primeError}\n</arc-context>`
        : "";

    if (!context) return;
    return {
      systemPrompt: `${event.systemPrompt}\n\n${context}`,
    };
  });

  pi.registerCommand("arc-refresh", {
    description: "Refresh cached arc prime context",
    handler: async (_args, ctx) => {
      const ok = await refreshPrime(ctx);
      if (ctx.hasUI) ctx.ui.notify(ok ? "arc context refreshed" : "arc prime failed", ok ? "info" : "error");
      sendArcMessage("Arc context refresh", ok ? "arc prime completed successfully." : `arc prime failed:\n\n\`\`\`\n${primeError}\n\`\`\``);
    },
  });

  pi.registerCommand("arc-prime", {
    description: "Show cached arc prime context, refreshing if needed",
    handler: async (_args, ctx) => {
      if (!primeCache && !primeError) await refreshPrime(ctx);
      if (primeCache) {
        sendArcMessage("Arc prime", `\`\`\`\n${primeCache}\n\`\`\``);
      } else {
        sendArcMessage("Arc prime unavailable", `\`\`\`\n${primeError || "No arc prime output."}\n\`\`\``);
      }
    },
  });

  pi.registerCommand("arc-onboard", {
    description: "Run arc onboard for the current project",
    handler: async (_args, ctx) => {
      await sendArcCommandOutput(ctx, "Arc onboard", ["onboard"], 60_000);
      await refreshPrime(ctx);
    },
  });

  pi.registerCommand("arc-which", {
    description: "Show which arc project is active",
    handler: async (_args, ctx) => {
      await sendArcCommandOutput(ctx, "Arc project resolution", ["which"], 30_000);
    },
  });

  pi.registerCommand("arc-subagents-sync", {
    description: "Write Arc specialist pi-subagents agent definitions to project or user scope",
    handler: async (args, ctx) => {
      const parsedArgs = parseArcSubagentScopeArg(args);
      if (parsedArgs.error) {
        if (ctx.hasUI) ctx.ui.notify("arc-subagents-sync failed", "error");
        sendArcMessage(
          "Arc subagents sync failed",
          `${parsedArgs.error}\n\nUsage:\n- \`/arc-subagents-sync\` (project scope)\n- \`/arc-subagents-sync project\`\n- \`/arc-subagents-sync user\``,
        );
        return;
      }

      const targetDir = resolveArcSubagentDir(parsedArgs.scope, ctx.cwd);
      await mkdir(targetDir, { recursive: true });

      const written: string[] = [];
      const skipped: ArcSubagentSyncSkip[] = [];
      const failed: ArcSubagentSyncSkip[] = [];

      for (const { source, target } of ARC_PI_SUBAGENTS) {
        const sourcePath = path.join(AGENTS_DIR, `${source}.md`);
        const targetPath = path.join(targetDir, `${target}.md`);

        try {
          const sourceMarkdown = await readFile(sourcePath, "utf8");
          const parsedSource = parseAgentMarkdown(sourceMarkdown);
          const resolvedModel = await modelPattern(parsedSource.model, ctx.cwd);
          const output = buildArcSubagentMarkdown(target, source, sourceMarkdown, parsedSource, resolvedModel);

          let existing: string | undefined;
          try {
            existing = await readFile(targetPath, "utf8");
          } catch {
            existing = undefined;
          }

          if (existing && !existing.includes(ARC_SUBAGENT_GENERATED_MARKER)) {
            skipped.push({
              file: targetPath,
              reason: "existing file is missing the generated marker; preserving user edits",
            });
            continue;
          }

          await writeFile(targetPath, output, "utf8");
          written.push(targetPath);
        } catch (error) {
          failed.push({
            file: targetPath,
            reason: error instanceof Error ? error.message : String(error),
          });
        }
      }

      if (ctx.hasUI) {
        ctx.ui.notify(
          `arc-subagents-sync wrote ${written.length}, skipped ${skipped.length}${failed.length ? `, failed ${failed.length}` : ""}`,
          failed.length > 0 ? "warning" : "info",
        );
      }

      const writtenText = written.length > 0 ? written.map((file) => `- \`${file}\``).join("\n") : "- none";
      const skippedText = skipped.length > 0 ? skipped.map((entry) => `- \`${entry.file}\` — ${entry.reason}`).join("\n") : "- none";
      const failedText = failed.length > 0 ? failed.map((entry) => `- \`${entry.file}\` — ${entry.reason}`).join("\n") : "- none";

      sendArcMessage(
        "Arc subagents sync",
        `Scope: **${parsedArgs.scope}**\nTarget directory: \`${targetDir}\`\n\nWritten/updated:\n${writtenText}\n\nSkipped:\n${skippedText}\n\nFailed:\n${failedText}\n\nNext steps:\n1. Run \`subagent({ action: "list" })\` to confirm the Arc specialists are available.\n2. Run \`/agents\` to inspect loaded agent definitions.\n3. Use \`/subagents-status\` to monitor active/recent async Arc specialist runs after launch; idle installed agents are listed by \`/agents\`, not the status overlay.\n4. Use Arc specialists (for example \`arc-spec-reviewer\`) for Arc gates instead of generic \`worker\` agents.`,
      );
    },
  });

  for (const { command, skill, description } of WORKFLOW_SKILLS) {
    pi.registerCommand(command, {
      description,
      handler: async (args) => {
        pi.sendUserMessage(`/skill:${skill}${args.trim() ? ` ${args.trim()}` : ""}`);
      },
    });
  }
}
